# This is a basic workflow to help you get started with Actions

name: daily_report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 6 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  workflow_call:
    secrets:
      XMU_ID:
        description: 'Your XMU ID'
        required: true
      XMU_PASSWORD:
        description: 'Your XMU Password'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: report
        env: 
          XMU_ID: ${{ secrets.XMU_ID }}
        run: |
          cd $GITHUB_WORKSPACE/bin/github_action/v1.2.0-x64-linux
          chmod +x ./daily_reporter
          echo $XMU_ID
          ./daily_reporter
