# This is a basic workflow to help you get started with Actions

name: 健康打卡

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 22 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sleep:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: sleep
        run: |
          cd $GITHUB_WORKSPACE/bin/github_action/
          bash sleep.sh
          
  # This workflow contains a single job called "build"
  daily_report:
    needs: sleep
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: report
        env: 
          SETTING: ${{ secrets.SETTING }}
        run: |
          cd $GITHUB_WORKSPACE/bin/github_action/
          chmod +x ./daily_reporter
          echo $SETTING > "report_setting.json"
          ulimit -c unlimited
          sudo ./daily_reporter ?> 1.out &
          sleep 20
          less 1.out
          sudo echo "Get coredump"
          cp core.* /var/crash
          sudo chmod -R +rwx /var/crash/*
      - uses: actions/upload-artifact@master # capture all crashes as build artifacts
        with:
          name: crashes
          path: /var/crash
